version: '3'

services:
  gisfast_db:
    image: postgis/postgis
    volumes:
      - C:\Users\limei\Documents\05_VSCode\gis_fast\postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: gisdb
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d gisdb" ]
      interval: 20s
      timeout: 10s
      retries: 10

  gisfast_app:
    image: gist_fast
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      gisfast_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app_user:app_password@gisfast_db:5432/gisdb
